### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by ShehabSalah** [khalilmansouri/mongoose-serial#18] opened 2022-06-20 14:30 UTC
I tried it but it didn't work.
So, I dropped the database the rebuilt it again and nothing changed

`let user = mongoose.model('User', UserSchema)
UserSchema.plugin(mongooseSerial, {
  field:"serialNumber",
  prefix: "ISC_",
  initCount:"yearly",
  separator: "_",
  digits: 6
})

module.exports.User = user`

**Comment by hamudeshahin** [comment] 2022-07-21 09:07
Hi @ShehabSalah !. 
Did you fix this error ? because i have same error

**Comment by amustaque97** [comment] 2022-07-21 16:22
Duplicate of https://github.com/khalilmansouri/mongoose-serial/issues/17

We can close this as well. @khalilmansouri

**Closed** 2022-07-25 20:08 UTC
